resolver: lts-13.5

packages:
- .

extra-deps:
- ../lapack-ffi
- ../netlib-comfort-array
- ../netlib-ffi
- ../comfort-array
- ../storable-complex

extra-lib-dirs:
  - J:/dev/projects/foreigner/installed/lib
